"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

type Props = { open: boolean; onClose: () => void; lang?: "fr" | "en" };
const industriesFr = ["BTP", "Services / PME", "Retail", "Immobilier", "Droit / conseil", "Industrie / manufacturing", "Autre"];
const challengesFr = ["Retrouver la bonne version", "Suivre les pièces manquantes", "Anticiper les échéances", "Sécuriser les accès", "Fluidifier les validations", "Transmettre la connaissance"];

export function FounderApplicationModal({ open, onClose, lang = "fr" }: Props) {
  const dialogRef = useRef<HTMLDialogElement>(null);
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle");
  const tr = (fr: string, en: string) => lang === "fr" ? fr : en;
  const industries = lang === "fr" ? industriesFr : ["Construction", "Services / SMEs", "Retail", "Real estate", "Legal / advisory", "Manufacturing", "Other"];
  const challenges = lang === "fr" ? challengesFr : ["Find the right version", "Track missing documents", "Anticipate deadlines", "Secure access", "Streamline approvals", "Transfer knowledge"];
  useEffect(() => { const d = dialogRef.current; if (!d) return; if (open && !d.open) d.showModal(); if (!open && d.open) d.close(); }, [open]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setState("sending");
    const form = event.currentTarget; const data = new FormData(form);
    const documentLocations = data.getAll("documentLocations"); const payload = Object.fromEntries(data.entries()); delete payload.documentLocations;
    try {
      const response = await fetch("/api/founder-applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...payload, documentLocations }) });
      if (!response.ok) throw new Error(); form.reset(); setState("success");
    } catch { setState("error"); }
  }
  function close() { setState("idle"); onClose(); }
  return <dialog ref={dialogRef} className="rg-application" onCancel={e => { e.preventDefault(); close(); }} onClose={onClose}><div className="rg-application__shell">
    <button className="rg-application__close" type="button" onClick={close} aria-label={tr("Fermer le formulaire", "Close form")}>{tr("Fermer", "Close")}&nbsp; ×</button>
    {state === "success" ? <div className="rg-application__success"><span aria-hidden="true">✓</span><p className="rg-eyebrow">{tr("CANDIDATURE REÇUE", "APPLICATION RECEIVED")}</p><h2>{tr("Merci.", "Thank you.")}<br />{tr("La suite reste humaine.", "What comes next stays human.")}</h2><p>{tr("Notre équipe étudiera votre situation. Si vos enjeux correspondent au cercle fondateur, nous vous proposerons un premier échange individuel par email.", "Our team will review your situation. If your needs align with the founding circle, we will invite you to an initial one-to-one conversation by email.")}</p><button type="button" className="rg-button rg-button--dark" onClick={close}>{tr("Revenir au site", "Return to the site")} →</button></div> : <>
      <header className="rg-application__head"><span className="rg-eyebrow">{tr("CERCLE FONDATEUR · CANDIDATURE", "FOUNDING CIRCLE · APPLICATION")}</span><h2>{tr("Parlez-nous de", "Tell us about")}<br /><span>{tr("votre réalité.", "your reality.")}</span></h2><p>{tr("Environ 3 minutes. Il n’y a ni achat, ni engagement. Chaque candidature est relue par notre équipe.", "About 3 minutes. There is no purchase or commitment. Every application is reviewed by our team.")}</p></header>
      <form onSubmit={submit}>
        <fieldset><legend><b>01</b><span>{tr("Vous et votre entreprise", "You and your business")}<small>{tr("Pour savoir avec qui nous échangeons.", "So we know who we are speaking with.")}</small></span></legend><div className="rg-form-grid"><label>{tr("Prénom", "First name")}<input name="firstName" required autoComplete="given-name" /></label><label>{tr("Nom", "Last name")}<input name="lastName" required autoComplete="family-name" /></label></div><label>{tr("Email professionnel", "Work email")}<input name="workEmail" type="email" required autoComplete="email" placeholder={tr("vous@entreprise.fr", "you@company.com")} /></label><div className="rg-form-grid"><label>{tr("Entreprise", "Company")}<input name="companyName" required autoComplete="organization" /></label><label>{tr("Votre fonction", "Job title")}<input name="jobTitle" required autoComplete="organization-title" /></label></div><div className="rg-form-grid"><label>{tr("Taille de l’entreprise", "Company size")}<select name="companySize" required defaultValue=""><option value="" disabled>{tr("Choisir", "Choose")}</option><option>1–9</option><option>10–49</option><option>50–249</option><option>250+</option></select></label><label>{tr("Secteur", "Industry")}<select name="industry" required defaultValue=""><option value="" disabled>{tr("Choisir", "Choose")}</option>{industries.map(x => <option key={x}>{x}</option>)}</select></label></div></fieldset>
        <fieldset><legend><b>02</b><span>{tr("Votre réalité documentaire", "Your document reality")}<small>{tr("Pour vérifier que nous pouvons résoudre un vrai problème.", "To check that we can solve a real problem.")}</small></span></legend><label>{tr("Où vivent aujourd’hui vos documents ?", "Where do your documents live today?")}<span className="rg-form-hint">{tr("Plusieurs réponses possibles", "Select all that apply")}</span><span className="rg-form-checks">{(lang === "fr" ? ["Emails", "Dossiers partagés", "SharePoint / Drive", "Outils métier", "Ordinateurs locaux", "Papier"] : ["Emails", "Shared folders", "SharePoint / Drive", "Business tools", "Local computers", "Paper"]).map(x => <span key={x}><input type="checkbox" name="documentLocations" value={x} /> {x}</span>)}</span></label><label>{tr("Votre principal blocage", "Your main challenge")}<select name="primaryChallenge" required defaultValue=""><option value="" disabled>{tr("Choisir le plus important", "Choose the most important")}</option>{challenges.map(x => <option key={x}>{x}</option>)}</select></label><label>{tr("Volume traité chaque mois", "Monthly document volume")}<select name="monthlyVolume" required defaultValue=""><option value="" disabled>{tr("Une estimation suffit", "An estimate is enough")}</option><option>{tr("Moins de 100 documents", "Fewer than 100 documents")}</option><option>100–500</option><option>500–2,000</option><option>{tr("Plus de 2 000 documents", "More than 2,000 documents")}</option></select></label><label>{tr("Racontez-nous un cas concret", "Tell us about a real use case")}<textarea name="useCase" required minLength={60} maxLength={700} rows={5} placeholder={tr("Ex. Nous perdons du temps à vérifier les attestations de nos sous-traitants avant chaque chantier…", "For example, we lose time checking subcontractor certificates before every project…")} /><span className="rg-form-hint">{tr("Une situation précise nous aide davantage qu’une liste de fonctionnalités.", "A specific situation helps us more than a feature list.")}</span></label></fieldset>
        <fieldset><legend><b>03</b><span>{tr("Votre participation", "Your participation")}<small>{tr("Pour construire avec des personnes réellement impliquées.", "To build with people who are genuinely involved.")}</small></span></legend><label>{tr("Quel est votre rôle dans ce sujet ?", "What is your role in this topic?")}<select name="involvementRole" required defaultValue=""><option value="" disabled>{tr("Choisir", "Choose")}</option><option>{tr("Je décide", "I make decisions")}</option><option>{tr("Je pilote le processus", "I lead the process")}</option><option>{tr("Je l’utilise au quotidien", "I use it daily")}</option><option>{tr("J’accompagne les équipes", "I support the teams")}</option></select></label><label>{tr("Pouvez-vous participer à un échange de 30–45 minutes ?", "Can you join a 30–45 minute conversation?")}<select name="interviewAvailability" required defaultValue=""><option value="" disabled>{tr("Choisir", "Choose")}</option><option value="yes">{tr("Oui", "Yes")}</option><option value="maybe">{tr("Peut-être, selon les dates", "Maybe, depending on dates")}</option><option value="no">{tr("Non", "No")}</option></select></label><label>{tr("Et à 2 ou 3 ateliers de co-construction sur 6–8 semaines ?", "And 2 or 3 co-design workshops over 6–8 weeks?")}<select name="codesignCommitment" required defaultValue=""><option value="" disabled>{tr("Choisir", "Choose")}</option><option value="yes">{tr("Oui", "Yes")}</option><option value="maybe">{tr("Peut-être", "Maybe")}</option><option value="no">{tr("Non", "No")}</option></select></label></fieldset>
        <label className="rg-form-consent"><input type="checkbox" name="consent" value="yes" required /><span>{tr("J’accepte que Remparia utilise ces informations uniquement pour étudier ma candidature et me contacter au sujet du cercle fondateur.", "I agree that Remparia may use this information only to review my application and contact me about the founding circle.")}</span></label><input className="rg-honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" />
        {state === "error" && <p className="rg-form-error" role="alert">{tr("L’envoi n’a pas abouti. Réessayez ou écrivez à contact@remparia.com.", "Submission failed. Try again or email contact@remparia.com.")}</p>}<button className="rg-button rg-button--dark rg-form-submit" type="submit" disabled={state === "sending"}>{state === "sending" ? tr("Envoi en cours…", "Sending…") : tr("Envoyer ma candidature ↗", "Submit my application ↗")}</button><p className="rg-form-footnote">{tr("Une candidature n’entraîne pas une acceptation automatique. Vous recevrez une réponse après étude.", "An application does not guarantee acceptance. You will receive a response after review.")}</p>
      </form>
    </>}
  </div></dialog>;
}
